version: '3.8'

services:
  backend:
    build: .
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/AppointmentScheduler?authSource=admin
      - DB_NAME=AppointmentScheduler
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: