apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-simulator-service
  labels:
    app: grade-simulator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-simulator-service
  template:
    metadata:
      labels:
        app: grade-simulator-service
    spec:
      containers:
      - name: grade-simulator-service
        image: ali142/grade-simulator-service:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /simulator/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /simulator/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: grade-simulator-service
spec:
  selector:
    app: grade-simulator-service
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort 