apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-simulator-backend
  labels:
    app: grade-simulator-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-simulator-backend
  template:
    metadata:
      labels:
        app: grade-simulator-backend
    spec:
      containers:
      - name: grade-simulator-backend
        image: ali142/grade-simulator-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: grade-simulator-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: grade-simulator-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: grade-simulator-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: grade-simulator-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grade-simulator-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /simulator/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /simulator/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 