apiVersion: v1
kind: ConfigMap
metadata:
  name: course-service-config
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/courses"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CACHE_TTL: "3600"
  CACHE_ENABLED: "true" 