apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: init-db
        image: adhamafis/course-service:latest
        command: ["python", "init_db.py"]
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: course-service-config
              key: DATABASE_URL
      restartPolicy: OnFailure 