apiVersion: batch/v1
kind: Job
metadata:
  name: seed-database
spec:
  template:
    spec:
      containers:
      - name: seed-database
        image: course-service:latest  # Use the same image as your main service
        command: ["python", "seed_db.py", "--force"]
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: course-service-config
                key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 1
