version: '3.8'

services:
  api:
    build: .
    container_name: course-api
    command: >
      bash -c "./wait-for-postgres.sh db &&
               ./wait-for-redis.sh redis &&
               python init_db.py &&
               uvicorn app.main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/courses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=3600
      - CACHE_ENABLED=true
    depends_on:
      - db
      - redis
    networks:
      - course-network

  prometheus:
    image: prom/prometheus:latest
    container_name: course-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - course-network
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: course-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - course-network
    depends_on:
      - prometheus

  db:
    image: postgres:14
    container_name: course-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    ports:
      - "5432:5432"
    networks:
      - course-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: course-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - course-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  course-network:
    driver: bridge 