package com.university.registration.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.university.registration.model.Student;
import com.university.registration.repository.StudentRepository;

@RestController
@RequestMapping("/api/students")
public class StudentController {

    @Autowired
    private StudentRepository studentRepository;

    @PostMapping("/addTestStudent")
    public ResponseEntity<Student> addTestStudent(@RequestParam String email) {
        Student student = new Student();
        student.setEmail(email);
        // Set other required fields with default or test values
        student.setFirstName("Test");
        student.setLastName("Student");
        student.setGpa(4.0);
        // Remove setting studentId as it is usually auto-generated by DB
        // student.setStudentId(null);

        Student savedStudent = studentRepository.save(student);
        return ResponseEntity.ok(savedStudent);
    }
}
