apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: novaxe/notification-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: mongo-uri
        - name: DATABASE_NAME
          value: "advising_app"
        - name: EMAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: email-address
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-secrets
              key: email-password
        - name: FRONTEND_URL
          value: "http://localhost:5173"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: notification-service