apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://nova:nova@cluster0.m1y8tvk.mongodb.net/"
  email-address: "novaxaboud@gmail.com"
  email-password: "ttsh mvqn vrcp rwps"