apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: notification-service