apiVersion: v1
kind: ConfigMap
metadata:
  name: course-api-config
data:
  DATABASE_URL: "postgresql://postgres:postgres@course-db:5432/courses"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "courses" 