name: Backend API Tests

on:
  push:
    branches: [ '*' ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: courses
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      working-directory: backend/course-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run migrations
      working-directory: backend/course-service
      run: |
        export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/courses
        alembic upgrade head
    
    - name: Test with pytest
      working-directory: backend/course-service
      run: |
        export DATABASE_URL=postgresql://postgres:postgres@localhost:5432/courses
        pytest --cov=app --cov-report=term-missing --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      if: success()
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false 