version: '3.8'

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: course-migrate
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/courses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=3600
      - CACHE_ENABLED=true
    depends_on:
      - db
      - redis
    networks:
      - course-network

  db:
    image: postgres:14
    container_name: course-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courses
    ports:
      - "5432:5432"
    networks:
      - course-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: course-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - course-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  course-network:
    driver: bridge 