"""add_is_core_and_level_columns

Revision ID: 88d01d87d974
Revises: add_missing_columns
Create Date: 2025-03-22 17:23:59.392667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '88d01d87d974'
down_revision = 'add_missing_columns'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Check if the categories table already exists
    if 'categories' not in inspector.get_table_names():
        op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
        op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    
    # Check if program_category table exists
    if 'program_category' not in inspector.get_table_names():
        op.create_table('program_category',
        sa.Column('course_id', sa.String(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], )
        )
    
    # Add columns to courses table if they don't exist
    courses_columns = [c['name'] for c in inspector.get_columns('courses')]
    if 'is_core' not in courses_columns:
        op.add_column('courses', sa.Column('is_core', sa.Boolean(), nullable=True))
    if 'level' not in courses_columns:
        op.add_column('courses', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'level')
    op.drop_column('courses', 'is_core')
    op.drop_table('program_category')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ### 