apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: student-service

apiVersion: v1
kind: Service
metadata:
  name: advising-service
  labels:
    app: advising-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: advising-service 