version: '3.8'

services:
  registration-service:
    build: .
    container_name: registration-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/registration_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=registration_db
    ports:
      - "3307:3306"  # Changed host port to 3307
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
