name: Backend CI/CD

on:
  push:
    branches: [ '*' ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    
    - name: Deploy to Kubernetes
      working-directory: backend/course-service/scripts
      run: |
        chmod +x deploy.sh
        ./deploy.sh
