name: Docker Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: builder
          load: true
          tags: cse455-advising:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build production image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: cse455-advising:prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test production image
        run: |
          docker run -d -p 8080:80 --name test-container cse455-advising:prod
          sleep 5
          curl -f http://localhost:8080 || exit 1
          docker logs test-container
          docker stop test-container 